import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import staffRouter from "./staff";
import notificationRouter from "./notifications";
import syncRouter from "./sync";
import systemRouter from "./system";
import entityRouter from "./entities";
import fileRouter from "./files";
import aiRouter from "./ai";
import propertyRouter from "./property";
import publicAccessRouter from "./publicAccess";
import organizationsRouter from "./organizations";
import scoresRouter from "./scores";
import timeClockRouter from "./timeClock";
import hrRouter from "./hr";
import nychaRouter from "./nycha";
import coverageRouter from "./coverage";
import companyFormsRouter from "./companyForms";
import joinRouter from "./join";
import workRequestsRouter from "./workRequests";
import aepRouter from "./aep";
import alertsRouter from "./alerts";
import pricingRouter from "./pricing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(organizationsRouter);
router.use(publicAccessRouter);
router.use(joinRouter);
router.use(workRequestsRouter);
router.use(aepRouter);
router.use(alertsRouter);
router.use(pricingRouter);
// Before the staff routers: its public DOF lookup must not hit their requireAuth.
router.use(propertyRouter);
router.use(companyFormsRouter);
router.use(nychaRouter);
router.use(coverageRouter);
router.use(staffRouter);
router.use(notificationRouter);
router.use(syncRouter);
router.use(systemRouter);
router.use(scoresRouter);
router.use(hrRouter);
router.use(entityRouter);
router.use(fileRouter);
router.use(aiRouter);
router.use(timeClockRouter);

export default router;
